name: ci-test

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test-repo-dispatch]

jobs:
  ci-test: 
    name: ci test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          BODY="${{ github.event.client_payload.message }}"
          gh issue create \
            --body "${BODY}" \
            --title "${{ github.event.client_payload.subject }}"

